apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: webapp-pvc 
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - "lke307548-501902-5dd05abe0000"
      containers:
        - name: webapp-container
          image: vincekazerr/webapp:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "125m"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: webapp-vol
              mountPath: /app/data
      volumes:
        - name: webapp-vol
          persistentVolumeClaim:
            claimName: webapp-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels: 
    job: node-api
    app: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32600
