apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: splunk-operator-app-download-pv  
  labels:  
    name: splunk-operator  
spec:  
  capacity:  
    storage: 10Gi  
  accessModes:  
  - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: "" 
  volumeMode: Filesystem  
  hostPath:  
    path: /mnt/data/splunk-operator-app-download 
