apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: pv-etc-splunk-s1-standalone-0  
  labels:  
    app.kubernetes.io/component: standalone  
    app.kubernetes.io/instance: splunk-s1-standalone  
    app.kubernetes.io/managed-by: splunk-operator  
    app.kubernetes.io/name: standalone  
    app.kubernetes.io/part-of: splunk-s1-standalone  
spec:  
  capacity:  
    storage: 10Gi  
  accessModes:  
    - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: ""  
  volumeMode: Filesystem  
  hostPath:  
    path: /mnt/data/splunk/etc-splunk-s1-standalone-0 
