import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import Header from "@/Components/header";

const mont = Montserrat({subsets: ["latin"]});



export const metadata: Metadata = {
  title: "Documentation Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mont.className}  `}
      >
        <div>
          <div >
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
